version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      DATABASE_URL: "mysql+pymysql://bryan:12345@db/main_database"
      BELVO_SECRET_KEY_ID: ${BELVO_SECRET_KEY_ID}
      BELVO_SECRET_KEY: ${BELVO_SECRET_KEY}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db
    env_file:
    - .env

