FROM python:3.9-slim

# Instalar dependencias de sistema necesarias para mysqlclient y pruebas
RUN apt-get update && apt-get install -y \
    gcc \
    default-libmysqlclient-dev \
    libmariadb-dev \
    pkg-config \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Establecer el directorio de trabajo
WORKDIR /code

# Copiar solo el archivo requirements.txt inicialmente
COPY ./requirements.txt /code/

# Instalar dependencias de Python, incluyendo pytest y herramientas de cobertura
RUN pip install --no-cache-dir --upgrade -r requirements.txt \
    && pip install pytest pytest-cov

# Copiar el resto del código de la aplicación
COPY ./app /code/app
COPY ./test /code/test  

ENV PYTHONPATH=/code


# Comando para ejecutar las pruebas usando pytest
CMD ["pytest", "/code/test"]
